services:

  # Dịch vụ cơ sở dữ liệu
  db:
    image: mysql:8.0
    restart: always # Luôn khởi động lại nếu dừng
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      # Đảm bảo tương thích (MySQL 8 mặc định dùng caching_sha2_password)
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Lưu trữ dữ liệu DB bền vững
    healthcheck: # Kiểm tra DB đã sẵn sàng
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s # Chờ trước khi bắt đầu kiểm tra

  # Dịch vụ Backend
  backend:
    build: ./task-management-backend # Build từ Dockerfile trong thư mục này
    ports:
      - "8080:8080"
    environment:
      # Cấu hình kết nối DB cho Spring Boot
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpassword
    depends_on:
      db:
        condition: service_healthy # Chờ DB khỏe mạnh hoàn toàn

  # Dịch vụ Frontend
  frontend:
    build: ./task-management-frontend # Build từ Dockerfile trong thư mục này
    ports:
      - "3000:3000"
    environment:
      # URL API Backend cho Frontend Next.js
      NEXT_PUBLIC_BACKEND_API_URL: http://backend:8080
    depends_on:
      backend:
        condition: service_started # Chờ Backend khởi động

# Định nghĩa các volume để lưu trữ dữ liệu
volumes:
  db_data: # Volume cho dữ liệu MySQL